<a href="https://colab.research.google.com/github/zzzer0-wav/Analysis_Cafe_Sales/blob/main/EDA_cafe_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Analysis Cafe Sales
Cafe Sales - Dirty Data for Cleaning Training

Overview

The Dirty Cafe Sales dataset contains 10,000 rows of synthetic data representing sales transactions in a cafe. This dataset is intentionally "dirty," with missing values, inconsistent data, and errors introduced to provide a realistic scenario for data cleaning and exploratory data analysis (EDA). It can be used to practice cleaning techniques, data wrangling, and feature engineering.
File Information

    File Name: dirty_cafe_sales.csv
    Number of Rows: 10,000
    Number of Columns: 8

| Column Name | Description |
| --- | --- |
| Transaction ID | A unique identifier for each transaction. Always present and unique. |
| Item | The name of the item purchased. May contain missing or invalid values (e.g., "ERROR"). |
| Quantity | The quantity of the item purchased. May contain missing or invalid values. |
| Price Per Unit | The price of a single unit of the item. May contain missing or invalid values. |
| Total Spent | The total amount spent on the transaction. Calculated as Quantity * Price Per Unit. |
| Payment Method | The method of payment used. May contain missing or invalid values (e.g., None, "UNKNOWN"). |
| Location | The location where the transaction occurred. May contain missing or invalid values. |
| Transaction Date | The date of the transaction. May contain missing or incorrect values. |

In [2]:
!pip install numpy pandas matplotlib

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Loading the dataset

In [4]:
url = 'https://raw.githubusercontent.com/zzzer0-wav/Analysis_Cafe_Sales/refs/heads/main/data/dirty_cafe_sales.csv'

In [5]:
df_origin = pd.read_csv(url)

In [6]:
df_origin.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [7]:
df = df_origin.copy()

### Initial diagnosis

In [8]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [10]:
print('Date types (raw):\n')
df.dtypes

Date types (raw):

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

Problem:

Numeric columns (Quantity, Price Per Unit, Total Spent)

Date columns (Transaction Date)

In [11]:
print('Missing values:\n')
missing = df.isna().sum()
missing_pct = (missing / len(df) * 100)
missing_report = pd.DataFrame({
    'count': missing,
    '%': missing_pct
})

missing_report[missing_report['count']>0]

Missing values:

                  count      %
Item                333   3.33
Quantity            138   1.38
Price Per Unit      179   1.79
Total Spent         173   1.73
Payment Method     2579  25.79
Location           3265  32.65
Transaction Date    159   1.59

In [12]:
print('Unique values:\n')

print('--- Item ---\n')
display(df['Item'].value_counts(dropna=False))

print('--- Payment method ---\n')
display(df['Payment Method'].value_counts(dropna=False))

print('--- Location ---\n')
display(df['Location'].value_counts(dropna=False))

Unique values:

--- Item ---

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

--- Payment method ---

Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

--- Location ---

Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [13]:
print("Fing lines with 'ERROR' or 'UNKNOWN'\n")
# display(df.isin(['ERROR', 'UNKNOWN']).any())
display(df.isin(['ERROR', 'UNKNOWN']).sum())
mask_error = df.isin(['ERROR', 'UNKNOWN']).any(axis=1).sum()
print(f"Lines with 'ERROR' or 'UNKNOWN': {mask_error.sum()}")

Fing lines with 'ERROR' or 'UNKNOWN'

Transaction ID        0
Item                636
Quantity            341
Price Per Unit      354
Total Spent         329
Payment Method      599
Location            696
Transaction Date    301
dtype: int64

Lines with 'ERROR' or 'UNKNOWN': 2845

### Data cleaning

If we dont have copy of dataset - WE HAVE TO MAKE IT HERE

df_origin = origin dataset

df = cope of origin dataset

In [14]:
print('Rename columns:\n')

df.columns = df.columns.str.strip()

df = df.rename(columns={
    'Transaction ID': 'transaction_id',
    'Item': 'item',
    'Quantity': 'quantity',
    'Price Per Unit': 'price_per_unit',
    'Total Spent': 'total_spent',
    'Payment Method': 'payment_method',
    'Location': 'location',
    'Transaction Date': 'transaction_date'
})

print(list(df.columns))

Rename columns:

['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent', 'payment_method', 'location', 'transaction_date']

In [15]:
# '   TRansaction Date    '.strip().lower().replace(' ', '_')

In [16]:
# '   TRansaction   Date    '.strip().lower().replace(' ', '_')

In [17]:
# '_'.join('   TRansaction   Date    '.lower().split())

In [18]:
# df.columns.str.lower().str.split()

In [19]:
# 'ERROR' / 'UNKNOWH' -> NaN
df.replace(['ERROR','UNKNOWN', 'error', 'unknown', ''], np.nan, inplace=True)
df.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [20]:
# Converting numeric columns
for col in ['quantity', 'price_per_unit', 'total_spent']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Converting date
df['transaction_date'] = pd.to_datetime(df['transaction_date'], errors='coerce')
# df['transaction_date'] = df_origin['Transaction Date'].copy()

In [21]:
print('Coverting columns:\n')
df.dtypes

Coverting columns:

transaction_id              object
item                        object
quantity                   float64
price_per_unit             float64
total_spent                float64
payment_method              object
location                    object
transaction_date    datetime64[ns]
dtype: object

In [22]:
# Extracting time signatures
df['year'] = df['transaction_date'].dt.year.astype('Int64')
df['month'] = df['transaction_date'].dt.month.astype('Int8')

# df['month_name'] = df['transaction_date'].dt.month_name()
df['month_name'] = df['transaction_date'].dt.strftime('%B')

df['weekday'] = df['transaction_date'].dt.day_name()
df['week'] = df['transaction_date'].dt.isocalendar().week.astype('Int8')


# display(df[['transaction_date', 'year', 'month', 'month_name', 'weekday', 'week']].dtypes)
df[['transaction_date', 'year', 'month', 'month_name', 'weekday', 'week']].head()

  transaction_date  year  month month_name    weekday  week
0       2023-09-08  2023      9  September     Friday    36
1       2023-05-16  2023      5        May    Tuesday    20
2       2023-07-19  2023      7       July  Wednesday    29
3       2023-04-27  2023      4      April   Thursday    17
4       2023-06-11  2023      6       June     Sunday    23

In [23]:
# Restoring total_spent (quantity * price)

mask_recoverable = (
    df['total_spent'].isna() &
    df['quantity'].notna() &
    df['price_per_unit'].notna()
)

df.loc[mask_recoverable, 'total_spent'] = (
    df.loc[mask_recoverable, 'quantity'] *
    df.loc[mask_recoverable, 'price_per_unit']
)

print(f"Restoring total_spent: {mask_recoverable.sum()} string (quantity * price) ")

Restoring total_spent: 462 string (quantity * price)

In [24]:
# dict of median prices
price_map = (
    df.dropna(subset=['item', 'price_per_unit'])
    .groupby('item')['price_per_unit']
    .median()
    .to_dict()
)

mask_price = df['price_per_unit'].isna() & df['item'].notna()

df.loc[mask_price, 'price_per_unit'] = df.loc[mask_price, 'item'].map(price_map)

print(f"Restoring price_per_unit: {mask_price.sum()} string (median per item) ")

Restoring price_per_unit: 479 string (median per item)

In [25]:
# Restoring total_spent (new price - median item)

mask_recoverable2 = (
    df['total_spent'].isna() &
    df['quantity'].notna() &
    df['price_per_unit'].notna()
)

df.loc[mask_recoverable2, 'total_spent'] = (
    df.loc[mask_recoverable2, 'quantity'] *
    df.loc[mask_recoverable2, 'price_per_unit']
)

print(f"Restoring total_spent: {mask_recoverable2.sum()} string (new price - median item) ")

Restoring total_spent: 17 string (new price - median item)

In [26]:
# fillna item -> mode
mode_item = df['item'].mode()[0]

# df['item'].fillna(mode_item, inplace=True)  # old version
df.fillna({'item': mode_item}, inplace=True)

In [27]:
# payment_method, location -> 'Unknown'
df.fillna(
    {
        'payment_method': 'Unknown',
        'location': 'Unknown'
    },
    inplace=True
)

In [28]:
# Delete transaction_date and quantity where NaT or NaN
before = len(df)

df.dropna(subset=['transaction_date', 'quantity'], inplace=True)

after = len(df)

print(f"Deleted {before - after} rows")

Deleted 914 rows

In [29]:
# Delete duplicates
df.duplicated().sum()  # 0
df.drop_duplicates(inplace=True)

In [30]:
(df.quantity <= 0).sum()  # 0
(df.price_per_unit <= 0).sum()  # 0
(df.total_spent <= 0).sum()  # 0

np.int64(0)

In [31]:
(df['quantity'].isna() & df['price_per_unit'].isna()).sum()

np.int64(0)

In [32]:
(df['quantity'].isna() | df['price_per_unit'].isna()).sum()

np.int64(48)

In [48]:
df.info()
# df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 9083 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    9083 non-null   object
 1   item              9083 non-null   object
 2   quantity          9083 non-null   float64
 3   price_per_unit    9038 non-null   float64
 4   total_spent       9038 non-null   float64
 5   payment_method    9083 non-null   object
 6   location          9083 non-null   object
 7   transaction_date  9083 non-null   datetime64[ns]
 8   year              9083 non-null   Int64
 9   month             9083 non-null   Int8
 10  month_name        9083 non-null   object
 11  weekday           9083 non-null   object
 12  week              9083 non-null   Int8
dtypes: Int64(1), Int8(2), datetime64[ns](1), float64(3), object(6)
memory usage: 895.9+ KB

In [34]:
df['price_per_unit'].isna().sum()

np.int64(48)

In [50]:
df.dropna(subset=['total_spent'], inplace=True)
print(f"Delete rows with NaN (df['total_spent'].isna() & df['price_per_unit'].isna())")

Delete rows with NaN (df['total_spent'].isna() & df['price_per_unit'].isna())

In [40]:
for col in ['item', 'payment_method', 'location']:
    df[col] = df[col].str.strip().str.title()

print(f'Text fields are standartized (title case)')

Text fields are standartized (title case)

In [43]:
mask_total_spent = (df['quantity'] * df['price_per_unit'] != df['total_spent'])
mask_total_spent.sum()

np.int64(45)

In [51]:
df.loc[mask_total_spent, 'total_spent'] = (
    df.loc[mask_total_spent, 'quantity'] * df.loc[mask_total_spent, 'price_per_unit']
)

In [52]:
price_map = (
    df.dropna(subset=['item', 'price_per_unit'])
    .groupby('item')['price_per_unit']
    .median()
    .to_dict()
)

mask_price = df['price_per_unit'].isna()
df.loc[mask_price, 'price_per_unit'] = df.loc[mask_price, 'item'].map(price_map)

In [53]:
mask_total = df['total_spent'].isna()
df.loc[mask_total, 'total_spent'] = (
    df.loc[mask_total, 'quantity'] * df.loc[mask_total, 'price_per_unit']
)

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9038 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    9038 non-null   object
 1   item              9038 non-null   object
 2   quantity          9038 non-null   float64
 3   price_per_unit    9038 non-null   float64
 4   total_spent       9038 non-null   float64
 5   payment_method    9038 non-null   object
 6   location          9038 non-null   object
 7   transaction_date  9038 non-null   datetime64[ns]
 8   year              9038 non-null   Int64
 9   month             9038 non-null   Int8
 10  month_name        9038 non-null   object
 11  weekday           9038 non-null   object
 12  week              9038 non-null   Int8
dtypes: Int64(1), Int8(2), datetime64[ns](1), float64(3), object(6)
memory usage: 891.4+ KB

### Cleaning results

In [90]:
# df_origin = name_your_origin_dataset
# df = name_your_clean_dataset

print('Cleaning results:\n')
print('=' * 28)

print(f'Rows before cleaning: {len(df_origin)}')
print(f'Rows after cleaning: {len(df)}')
print(f'Loss: {len(df_origin) - len(df)} ({(len(df_origin) - len(df)) / len(df_origin) * 100:.1f}%)')

print('\n--- Residual gaps ---')
remaining = df.isna().sum()
print(remaining[remaining > 0] if remaining.any() else 'No gaps')

print('\n--- Data types after cleanup: ---')
print(df.dtypes)

print('\n--- Statisticts: ---')
print(df[['quantity', 'price_per_unit', 'total_spent']].describe().round(2))

Cleaning results:

============================
Rows before cleaning: 10000
Rows after cleaning: 9038
Loss: 962 (9.6%)

--- Residual gaps ---
No gaps

--- Data types after cleanup: ---
transaction_id              object
item                        object
quantity                   float64
price_per_unit             float64
total_spent                float64
payment_method              object
location                    object
transaction_date    datetime64[ns]
year                         Int64
month                         Int8
month_name                  object
weekday                     object
week                          Int8
dtype: object

--- Statisticts: ---
       quantity  price_per_unit  total_spent
count   9038.00         9038.00      9038.00
mean       3.02            2.95         8.93
std        1.42            1.28         6.00
min        1.00            1.00         1.00
25%        2.00            2.00         4.00
50%        3.00            3.00         8.00
75%        4.00            4.00        12.00
max        5.00            5.00        25.00

In [67]:
print(f"Всего строк: {len(df)}")
print(df[['price_per_unit', 'total_spent', 'quantity', 'transaction_date']].isna().sum())

Всего строк: 9038
price_per_unit      0
total_spent         0
quantity            0
transaction_date    0
dtype: int64